"""empty message

Revision ID: dffcec0f3d01
Revises: 
Create Date: 2018-09-11 06:53:14.194381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffcec0f3d01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector')
    # ### end Alembic commands ###
